### PR TITLE
Add LSP to the Binder image

### LINKED ISSUE #24: Add LSP extension to the binder image
### Problem

I like to use the the playground for quickly creating a demonstration of API usage when someone asks for help. However, editing is error prone without the coding assistance features.

### Proposed Solution

Add the LSP extension with a JavaScript/TypeScript language server to the Binder image. This will allow to quickly prototype very small snippets on binder smoothly.

### PR DESCRIPTION
**Pull request by krassowski**
Closes #24.

Binder: https://mybinder.org/v2/gh/krassowski/jupyterlab-plugin-playground/add-lsp?urlpath=lab

Screenshot from 2021-10-24 14-21-40

Note: we can hold this while I investigate migrating to a newer server (https://github.com/jupyter-lsp/jupyterlab-lsp/pull/697) and we could improve the default theme of the completer so that the detail is shown below the label not next to it (so it is not as spread out).

### CODE REVIEW

**Comment by krassowski** [comment]
Instead of babel we could try [sucrase](https://github.com/alangpierce/sucrase) as in https://github.com/ipython/ipython/issues/13376 - definitely worth experimenting.

**Comment by bollwyvl** [comment]
> compile with tsc ... sucrase

Hmm... I think figuring out a way to use the in-browser equivalent of `tsc` in the browser is going to give a developer better bang for their buck than `babel` or `sucrase`. While it is a bit heavy, it's the devil we know, and is going to have the best tooling.

On the broader point: the distribution of typings (or LSIF) should probably become a thing we by enable by default in e.g. `@jupyterlab/builder` and/or `extension-cookiecutter-ts`, depending on the work required.

Specifically on `sucrase`: while it seems to do a lot of nice things for interactive work, much like babel, some of the tricks it enables might not transfer well into a "production" extension.

**Comment by krassowski** [comment]
This now works (as in "the state is acceptable") but because the TypeScript filter expects the client to filter completions on their side we need to implement this to make it actually more useful; I opened https://github.com/jupyter-lsp/jupyterlab-lsp/issues/728.

**Comment by krassowski** [comment]
Ok, going for `tsc` is actually feasible. We can use transformers to swap the imports with whatever we like (tokens for `@jupyterlab/` and `require`s for anything else. Webpacking is an issue but there are know workarounds: https://github.com/microsoft/TypeScript/issues/39436

**Review by jtpio — APPROVED** [review]
Looks good on Binder, thanks!

image

**Pull request merged**
